2024-05-02 16:53:57,277 INFO    StreamThr :83873 [internal.py:wandb_internal():87] W&B internal server running at pid: 83873, started at: 2024-05-02 16:53:57.276867
2024-05-02 16:53:57,279 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: status
2024-05-02 16:53:57,280 INFO    WriterThread:83873 [datastore.py:open_for_write():85] open: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_165357-4ylu9rl0/run-4ylu9rl0.wandb
2024-05-02 16:53:57,282 DEBUG   SenderThread:83873 [sender.py:send():334] send: header
2024-05-02 16:53:57,288 DEBUG   SenderThread:83873 [sender.py:send():334] send: run
2024-05-02 16:53:57,289 INFO    SenderThread:83873 [sender.py:_maybe_setup_resume():721] checking resume status for None/nyc_airbnb/4ylu9rl0
2024-05-02 16:53:58,223 ERROR   SenderThread:83873 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 16:53:58,223 ERROR   SenderThread:83873 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 16:53:59,613 ERROR   SenderThread:83873 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 16:53:59,613 ERROR   SenderThread:83873 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 16:54:02,091 ERROR   SenderThread:83873 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 16:54:02,091 ERROR   SenderThread:83873 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 16:54:02,091 INFO    SenderThread:83873 [retry.py:__call__():169] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 128, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 241, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-02 16:54:02,289 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:07,290 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:08,204 ERROR   SenderThread:83873 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 16:54:08,204 ERROR   SenderThread:83873 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 16:54:12,291 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:17,292 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:17,695 ERROR   SenderThread:83873 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 16:54:17,696 ERROR   SenderThread:83873 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 16:54:22,294 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:27,295 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:32,296 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:35,951 ERROR   SenderThread:83873 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 16:54:35,952 ERROR   SenderThread:83873 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 16:54:37,298 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:42,299 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:47,300 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:52,301 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 16:54:57,302 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 16:54:57,304 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 16:54:57,304 DEBUG   SenderThread:83873 [sender.py:send():343] Record cancelled: run
2024-05-02 16:54:57,304 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: status_report
2024-05-02 16:54:59,714 DEBUG   HandlerThread:83873 [handler.py:handle_request():144] handle_request: shutdown
2024-05-02 16:54:59,714 INFO    HandlerThread:83873 [handler.py:finish():841] shutting down handler
2024-05-02 16:55:00,305 INFO    WriterThread:83873 [datastore.py:close():299] close: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_165357-4ylu9rl0/run-4ylu9rl0.wandb
2024-05-02 16:55:00,305 INFO    SenderThread:83873 [sender.py:finish():1491] shutting down sender
