2024-05-02 19:24:31,208 INFO    StreamThr :25340 [internal.py:wandb_internal():87] W&B internal server running at pid: 25340, started at: 2024-05-02 19:24:31.207311
2024-05-02 19:24:31,212 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: status
2024-05-02 19:24:31,214 INFO    WriterThread:25340 [datastore.py:open_for_write():85] open: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_192431-4ylu9rl0/run-4ylu9rl0.wandb
2024-05-02 19:24:31,215 DEBUG   SenderThread:25340 [sender.py:send():334] send: header
2024-05-02 19:24:31,224 DEBUG   SenderThread:25340 [sender.py:send():334] send: run
2024-05-02 19:24:31,226 INFO    SenderThread:25340 [sender.py:_maybe_setup_resume():721] checking resume status for None/nyc_airbnb/4ylu9rl0
2024-05-02 19:24:32,087 ERROR   SenderThread:25340 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 19:24:32,087 ERROR   SenderThread:25340 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 19:24:34,471 ERROR   SenderThread:25340 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 19:24:34,471 ERROR   SenderThread:25340 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 19:24:36,226 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:24:37,247 ERROR   SenderThread:25340 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 19:24:37,248 ERROR   SenderThread:25340 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 19:24:37,248 INFO    SenderThread:25340 [retry.py:__call__():169] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 128, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 241, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-02 19:24:41,228 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:24:42,030 ERROR   SenderThread:25340 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 19:24:42,030 ERROR   SenderThread:25340 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 19:24:46,230 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:24:51,158 ERROR   SenderThread:25340 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 19:24:51,158 ERROR   SenderThread:25340 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 19:24:51,232 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:24:56,235 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:25:01,237 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:25:06,239 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:25:09,857 ERROR   SenderThread:25340 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 19:25:09,858 ERROR   SenderThread:25340 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 19:25:11,240 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:25:16,243 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:25:21,245 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:25:26,246 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 19:25:31,248 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 19:25:31,248 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 19:25:31,249 DEBUG   SenderThread:25340 [sender.py:send():343] Record cancelled: run
2024-05-02 19:25:31,249 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: status_report
2024-05-02 19:25:33,646 DEBUG   HandlerThread:25340 [handler.py:handle_request():144] handle_request: shutdown
2024-05-02 19:25:33,646 INFO    HandlerThread:25340 [handler.py:finish():841] shutting down handler
2024-05-02 19:25:34,250 INFO    SenderThread:25340 [sender.py:finish():1491] shutting down sender
2024-05-02 19:25:34,250 INFO    WriterThread:25340 [datastore.py:close():299] close: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_192431-4ylu9rl0/run-4ylu9rl0.wandb
