2024-05-02 17:46:38,020 INFO    StreamThr :1075 [internal.py:wandb_internal():87] W&B internal server running at pid: 1075, started at: 2024-05-02 17:46:38.019802
2024-05-02 17:46:38,024 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: status
2024-05-02 17:46:38,028 INFO    WriterThread:1075 [datastore.py:open_for_write():85] open: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_174638-4ylu9rl0/run-4ylu9rl0.wandb
2024-05-02 17:46:38,029 DEBUG   SenderThread:1075 [sender.py:send():334] send: header
2024-05-02 17:46:38,039 DEBUG   SenderThread:1075 [sender.py:send():334] send: run
2024-05-02 17:46:38,041 INFO    SenderThread:1075 [sender.py:_maybe_setup_resume():721] checking resume status for None/nyc_airbnb/4ylu9rl0
2024-05-02 17:46:38,980 ERROR   SenderThread:1075 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:46:38,980 ERROR   SenderThread:1075 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:46:40,256 ERROR   SenderThread:1075 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:46:40,256 ERROR   SenderThread:1075 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:46:42,701 ERROR   SenderThread:1075 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:46:42,701 ERROR   SenderThread:1075 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:46:42,701 INFO    SenderThread:1075 [retry.py:__call__():169] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 128, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 241, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-02 17:46:43,041 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:46:47,375 ERROR   SenderThread:1075 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:46:47,375 ERROR   SenderThread:1075 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:46:48,042 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:46:53,045 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:46:57,355 ERROR   SenderThread:1075 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:46:57,356 ERROR   SenderThread:1075 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:46:58,046 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:03,047 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:08,049 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:13,051 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:15,666 ERROR   SenderThread:1075 [internal_api.py:execute():244] 409 response executing GraphQL.
2024-05-02 17:47:15,666 ERROR   SenderThread:1075 [internal_api.py:execute():245] {"errors":[{"message":"run 4ylu9rl0 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-02 17:47:18,053 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:23,055 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:28,056 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:33,059 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: keepalive
2024-05-02 17:47:38,060 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 17:47:38,061 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: cancel
2024-05-02 17:47:38,062 DEBUG   SenderThread:1075 [sender.py:send():343] Record cancelled: run
2024-05-02 17:47:38,063 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: status_report
2024-05-02 17:47:40,509 DEBUG   HandlerThread:1075 [handler.py:handle_request():144] handle_request: shutdown
2024-05-02 17:47:40,509 INFO    HandlerThread:1075 [handler.py:finish():841] shutting down handler
2024-05-02 17:47:41,063 INFO    SenderThread:1075 [sender.py:finish():1491] shutting down sender
2024-05-02 17:47:41,064 INFO    WriterThread:1075 [datastore.py:close():299] close: /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_174638-4ylu9rl0/run-4ylu9rl0.wandb
